=== pmattd/survival/src/main/resources/narrative/narrative.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns:common="http://CommonTypesNamespace/CommonTypes">

    <xs:import schemaLocation="../common-types.xsd"
               namespace="http://CommonTypesNamespace/CommonTypes"/>

    <xs:element name="narrative">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dialog" type="dialog" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="dialog">
        <xs:sequence>
            <xs:element name="interaction" type="interaction" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="start" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="interaction">
        <xs:sequence>
            <xs:element name="choice" type="choice" maxOccurs="1" minOccurs="0"/>
            <xs:element name="simple-text" type="simple-text" maxOccurs="1" minOccurs="0"/>
            <xs:element name="combat" type="combat" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>


    <xs:complexType name="choice">
        <xs:sequence>
            <xs:element name="text" type="common:text" minOccurs="1" maxOccurs="1"/>
            <xs:element name="option" type="option" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="text" type="common:text"/>
            <xs:element name="next" type="xs:IDREF"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>

    <xs:complexType name="simple-text">
        <xs:sequence>
            <xs:element name="text" type="common:text"/>
            <xs:element name="next" type="xs:IDREF" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="combat">
        <xs:sequence>
            <xs:element name="text" type="common:text"/>
            <xs:element name="hostile-group-ref" type="common:text"/>
            <xs:element name="next" type="xs:IDREF" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== pmattd/survival/src/main/resources/narrative/narrative.xml
<?xml version="1.0" encoding="UTF-8"?>

<narrative xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="narrative.xsd">
    <dialog id="dia1" start="step1">

        <interaction id="step1">
            <choice>
                <text key="inter.berries">Will you eat the berries</text>
                <option>
                    <text>yes</text>
                    <next>textDie</next>
                </option>
                <option>
                    <text>no</text>
                    <next>textLive</next>
                </option>
            </choice>
        </interaction>

        <interaction id="textDie">
            <simple-text>
                <text>you die</text>
                <next>textHorribly</next>
            </simple-text>
        </interaction>

        <interaction id="textLive">
            <simple-text>
                <text>you live</text>
            </simple-text>
        </interaction>

        <interaction id="textHorribly">
            <simple-text>
                <text>horribly!</text>
            </simple-text>
        </interaction>

    </dialog>

    <dialog id="petrolStation" start="petrolStart">
        <interaction id="petrolStart">
            <combat>
                <text>you see some hostiles</text>
                <hostile-group-ref>petrolCombat</hostile-group-ref>
            </combat>
        </interaction>
    </dialog>


</narrative>

=== pmattd/survival/src/test/resources/narrative/narrative_test.xml
<?xml version="1.0" encoding="UTF-8"?>

<narrative xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="narrative.xsd">
    <dialog id="dia1" start="step1">

        <interaction id="step1">
            <choice>
                <text key="inter.berries">Will you eat the berries</text>
                <option>
                    <text>I will</text>
                    <next>textDie</next>
                </option>
                <option>
                    <text>I wont</text>
                    <next>textLive</next>
                </option>
            </choice>
        </interaction>


        <interaction id="textLive">
            <simple-text>
                <text>you live</text>
                <next>end</next>
            </simple-text>
        </interaction>

        <interaction id="textDie">
            <simple-text>
                <text>you die horribly</text>
                <next>end</next>
            </simple-text>
        </interaction>

        <interaction id="end">
            <simple-text>
                <text>the end</text>
            </simple-text>
        </interaction>

    </dialog>

    <dialog id="petrolStation" start="petrolStart">
        <interaction id="petrolStart">
            <combat>
                <text>you see some hostiles</text>
                <hostile-group-ref>petrolCombat</hostile-group-ref>
            </combat>
        </interaction>
    </dialog>

</narrative>
