=== pmattd/survival/src/main/resources/translations/translations.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="translations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="translation" type="translation" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="translation">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:ID"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== pmattd/survival/src/main/resources/translations/core_translations_en.xml
<?xml version="1.0" encoding="UTF-8"?>

<translations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="translations.xsd">

    <translation key="options.dialog">Dialog</translation>
    <translation key="options.travel">Travel</translation>
    <translation key="options.create.hero">Create Hero</translation>
    <translation key="options.relocate">Relocate</translation>
    <translation key="options.scavenge">Scavenge</translation>
    <translation key="options.scavenge.collect">Collect the results of the scavenge</translation>
    <translation key="options.fight">Fight</translation>
    <translation key="options.quit">Quit</translation>

    <translation key="scavenge.no.supplies">you find nothing</translation>

    <translation key="interaction.next">continue</translation>

    <translation key= "hero.creation.title">Create your survivor</translation>
    <translation key="hero.creation.nameinput.title">Name</translation>

</translations>

=== pmattd/survival/src/main/resources/translations/translations_en.xml
<?xml version="1.0" encoding="UTF-8"?>

<translations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="translations.xsd">

    <!-- game config -->

    <translation key="inter.berries">will you partake of the berries</translation>

    <translation key="outerwall.area.desc">you are at the outerwall</translation>
    <translation key="outerwall.start.location.desc">north you can see what looks like a small village</translation>
    <translation key="outerwall.direction.north">head north</translation>

    <translation key="bov.desc">burnt out village</translation>
    <translation key="bov.ps.desc">an abandoned petrol station</translation>
    <translation key="bov.house.desc">an abandoned house</translation>
    <translation key="bov.ps.scavange">you find some tinned food and drinks</translation>
    <translation key="bov.house.scavange">you find plenty of food</translation>




</translations>
