=== pmattd/survival/src/main/resources/area/area-map.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns:common="http://CommonTypesNamespace/CommonTypes">

    <xs:import schemaLocation="../common-types.xsd"
               namespace="http://CommonTypesNamespace/CommonTypes"/>

    <xs:element name="area-map">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="area" type="area" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="area-start" type="xs:IDREF" use="required"/>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="area">
        <xs:sequence>
            <xs:element name="title" type="common:text" minOccurs="1" maxOccurs="1"/>
            <xs:element name="desc" type="common:text" minOccurs="1" maxOccurs="1"/>
            <xs:element name="directions" type="directions" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="location" type="location" minOccurs="1" maxOccurs="unbounded"/>

        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>


    <xs:complexType name="directions">
        <xs:sequence>
            <xs:element name="direction" type="direction" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="direction">
        <xs:sequence>
            <xs:element name="text" type="common:text" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="area-id" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="location">
        <xs:sequence>
            <xs:element name="title" type="common:text" minOccurs="1" maxOccurs="1"/>
            <xs:element name="desc" type="common:text" minOccurs="1" maxOccurs="1"/>
            <xs:element name="supplies" type="supplies" minOccurs="0" maxOccurs="10"/>
            <xs:element name="arrival-event" type="xs:string" minOccurs="0" maxOccurs="10"/>

        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="supplies">
        <xs:sequence>
            <xs:element name="scavenge-text" type="common:text" minOccurs="1" maxOccurs="1"/>
            <xs:element name="food" type="xs:int" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== pmattd/survival/src/test/resources/area/area-map_test.xml
<?xml version="1.0" encoding="UTF-8"?>

<area-map
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="area-map.xsd"

        area-start="london">

    <area id="london">
        <title>London</title>
        <desc key="london.start">The city of london</desc>
        <directions>
            <direction area-id="north.london">
                <text>you can head to north london to visit nick</text>
            </direction>
            <direction area-id="south.london">
                <text>you can head to south london to head for the coast</text>
            </direction>
        </directions>
        <location id="london-pharmacy">
            <title>pharmacyTitle</title>
            <desc>pharmacy</desc>
        </location>
        <location id="london-petrol">
            <desc>petrol station</desc>
        </location>
    </area>

    <area id="north.london">
        <desc>south london</desc>
        <location id="nlondon-nick">
            <desc>nicks house</desc>
            <supplies>
                <scavenge-text>scavengeText</scavenge-text>
                <food>5</food>
            </supplies>
        </location>
    </area>


    <area id="south.london">
        <desc>south london</desc>
        <location id="slondon-train">
            <desc>train station</desc>
        </location>
    </area>

</area-map>

=== pmattd/survival/src/main/resources/area/area-map.xml
<?xml version="1.0" encoding="UTF-8"?>

<area-map
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="area-map.xsd"

        area-start="outerwall">

    <area id="outerwall">
        <title>the outerwall</title>
        <desc>the outerwall</desc>
        <directions>
            <direction area-id="burnt.out.village">
                <text>you can head to north into the wilderness</text>
            </direction>
        </directions>
        <location id="outerwall.start">
            <title>the outerwall</title>
            <desc>the outerwall</desc>
            <arrival-event>dia1</arrival-event>
        </location>
    </area>

    <area id="burnt.out.village">
        <title>burnt out village</title>
        <desc>burnt out village</desc>
        <location id="petrol.station">
            <title>abandoned petrol station</title>
            <desc>an abandoned petrol station</desc>
            <supplies>
                <scavenge-text>you find some tinned food and drinks</scavenge-text>
                <food>5</food>
            </supplies>
<!--
            <arrival-event>petrolStation</arrival-event>
-->
        </location>
        <location id="bov.house">
            <title>abandoned house</title>
            <desc>an abandoned house</desc>
            <supplies>
                <scavenge-text>you find plenty of food</scavenge-text>
                <food>10</food>
            </supplies>
        </location>
    </area>

</area-map>
